#!/usr/bin/env python3
"""
Claude Code hook to prevent manual edits to Drizzle ORM migration files.

Drizzle migrations are auto-generated by drizzle-kit and should NEVER be
manually edited. This hook blocks Edit/Write operations on *.sql files
in the drizzle/ directory.

To modify the schema:
1. Edit apps/api/src/db/schema.ts
2. Run: cd apps/api && bun run db:generate
3. Run: cd apps/api && bun run db:migrate
"""
import json
import sys
import re

try:
    input_data = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)  # Allow on parse error (fail open)

tool_name = input_data.get("tool_name", "")
tool_input = input_data.get("tool_input", {})
file_path = tool_input.get("file_path", "")

# Block edits to Drizzle migration files
blocked_patterns = [
    r"apps/api/drizzle/.*\.sql$",      # Migration SQL files
    r"apps/api/drizzle/meta/.*\.json$", # Migration metadata/snapshots
]

if tool_name in ["Edit", "Write"]:
    for pattern in blocked_patterns:
        if re.search(pattern, file_path):
            print(
                f"BLOCKED: Cannot edit Drizzle migration file: {file_path}\n\n"
                f"Migration files are auto-generated and must NOT be manually edited.\n\n"
                f"To modify the database schema:\n"
                f"  1. Edit apps/api/src/db/schema.ts\n"
                f"  2. Run: cd apps/api && bun run db:generate\n"
                f"  3. Run: cd apps/api && bun run db:migrate",
                file=sys.stderr
            )
            sys.exit(2)  # Exit code 2 = block the operation

sys.exit(0)  # Allow the edit
