version: "2"

linters:
  default: standard
  enable:
    - gosec # Security issues
    - gocritic # Opinionated style checks
    - misspell # Spelling mistakes
    - errname # Error naming conventions
    - exhaustive # Exhaustive switch statements

  settings:
    govet:
      enable:
        - shadow
        - nilness

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

    gosec:
      excludes:
        - G104 # Unhandled errors (too noisy)

run:
  timeout: 5m
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      print-linter-name: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
